version: "3.7"
services:

  app_wallet_x:
    build:
      context: infra
      dockerfile: dockerfiles/app.dockerfile
    container_name: app_wallet_x
    restart: unless-stopped
    working_dir: /var/www/
    env_file:
      - application/.env
    volumes:
      - ./application:/var/www/
      - ./application/supervisor/conf.d:/etc/supervisor/conf.d
    networks:
      - network_walletx

  db_wallet_x:
    image: mysql:8.0
    container_name: db_wallet_x
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PORT: ${DB_PORT}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./infra/mysql_data:/var/lib/mysql
    networks:
      - network_walletx

  nginx_wallet_x:
    image: nginx:1.20-alpine
    container_name: nginx_wallet_x
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./application:/var/www
      - ./infra/nginx:/etc/nginx/templates
    networks:
      - network_walletx

  redis_wallet_x:
    image: redis
    container_name: redis_wallet_x
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./infra/redis_data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - network_walletx

networks:
  network_walletx:
    driver: bridge
